services:
  main_db:
    image: postgres
    container_name: music_base
    shm_size: 128mb
    environment:
      POSTGRES_HOST: "${POSTGRES_HOST}"
      POSTGRES_PORT: "${POSTGRES_PORT}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_USER: "${POSTGRES_USERNAME}"
    expose:
      - "${POSTGRES_PORT}"
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    command: -p ${POSTGRES_PORT}
    # volumes:
    #   - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: unless-stopped
    networks:
      - db_net

  go_local:
    build:
      context: ./go/local_api_handlers/
      dockerfile: Dockerfile
    container_name: go_local
    depends_on:
      - main_db
    ports:
      - "7557:7557"
    restart: unless-stopped
    networks:
      - db_net
    env_file:
      - .env

  go_outer:
    build:
      context: ./go/outer_api_handlers/
      dockerfile: Dockerfile
    container_name: go_outer
    depends_on:
      - main_db
    ports:
      - "7558:7558"
    restart: unless-stopped
    networks:
      - db_net
    env_file:
      - .env
  
  swagger-ui:
    image: swaggerapi/swagger-ui
    ports:
      - "8080:8080"
    environment:
      - SWAGGER_JSON=/mnt/openapi.yaml
    volumes:
      - ./openapi.yaml:/mnt/openapi.yaml
    networks:
      - db_net

networks:
  db_net:
    driver: bridge